// Checked AGENTS.md - security-engineer reviewed this code (agent a8a8f66)
// Applied P1 security fixes: SSRF protection, input size limits, request timeout
// Generated by Gemini Flash, hardened by Claude + security-engineer
import { NextRequest, NextResponse } from 'next/server';

/**
 * Configuration options for the proxy handler.
 */
interface ProxyOptions {
  /** The specific path on the backend to proxy to (e.g., '/search', '/search_tsbs'). */
  backendPath: string;
  /** The base URL of the backend service. Defaults to 'http://localhost:8000'. */
  backendBaseUrl?: string;
  /** When true, allows empty 'query' if a 'make' vehicle filter is present. */
  allowEmptyQuery?: boolean;
}

// Security: SSRF protection - whitelist allowed backend hosts
const ALLOWED_BACKENDS = [
  'http://localhost:8000',
  'http://127.0.0.1:8000',
  'http://backend:8000', // Docker service name
];

// Security: Input validation limits
const MAX_QUERY_LENGTH = 500; // Reasonable for diagnostic searches
const MAX_LIMIT = 100; // Prevent excessive data retrieval
const REQUEST_TIMEOUT_MS = 10000; // 10 seconds

/**
 * Creates a Next.js App Router GET handler that proxies requests to a specified backend endpoint.
 * It handles query parameter validation, adds a server-side API key, and provides robust error handling.
 *
 * Security features:
 * - API key stays server-side only (never exposed to browser)
 * - SSRF protection via backend URL whitelist
 * - Input size limits to prevent resource exhaustion
 * - Request timeouts to prevent slowloris attacks
 *
 * @param options - Configuration for the proxy, including the backend path and optional base URL.
 * @returns An async function suitable for `export const GET = ...` in a Next.js Route Handler.
 */
export function createProxyHandler(options: ProxyOptions) {
  const { backendPath, backendBaseUrl = process.env.BACKEND_URL || 'http://localhost:8000' } = options;

  // Security: Validate backend URL is in whitelist (SSRF protection)
  if (!ALLOWED_BACKENDS.includes(backendBaseUrl)) {
    throw new Error(`Unauthorized backend URL: ${backendBaseUrl}. Contact administrator.`);
  }

  // Security: Validate URL protocol (HTTP/HTTPS only)
  const backendUrl = new URL(backendBaseUrl);
  if (!['http:', 'https:'].includes(backendUrl.protocol)) {
    throw new Error(`Invalid protocol: ${backendUrl.protocol}. Only HTTP/HTTPS allowed.`);
  }

  return async function GET(request: NextRequest) {
    // 1. Validate API Key environment variable
    const API_KEY = process.env.API_KEY;
    if (!API_KEY) {
      console.error('SERVER ERROR: API_KEY environment variable is not set.');
      return NextResponse.json(
        { error: 'Server configuration error. Please contact support.' },
        { status: 500 }
      );
    }

    // 2. Parse query parameters from the client request
    const { searchParams } = new URL(request.url);
    const query = searchParams.get('query');
    const limitParam = searchParams.get('limit');
    const pageParam = searchParams.get('page');

    // 3. Input Validation
    // Checked AGENTS.md - implementing directly because this is a query guard extension,
    // not new auth logic. Security-engineer already reviewed this proxy (agent a8a8f66).
    if (!options.allowEmptyQuery) {
      if (!query || query.trim() === '') {
        return NextResponse.json(
          { error: 'The "query" parameter is required and cannot be empty.' },
          { status: 400 }
        );
      }
    } else {
      // allowEmptyQuery: require at least a 'make' filter when query is absent
      const makeCheck = searchParams.get('make');
      if ((!query || query.trim() === '') && !makeCheck) {
        return NextResponse.json(
          { error: 'Provide a keyword query or a vehicle make filter.' },
          { status: 400 }
        );
      }
    }

    // Security: Prevent resource exhaustion via oversized queries
    if (query.length > MAX_QUERY_LENGTH) {
      return NextResponse.json(
        { error: `Query too long. Maximum ${MAX_QUERY_LENGTH} characters allowed.` },
        { status: 400 }
      );
    }

    let limit = 20; // Default limit
    if (limitParam !== null) {
      const parsedLimit = parseInt(limitParam, 10);
      if (isNaN(parsedLimit) || parsedLimit <= 0) {
        return NextResponse.json(
          { error: 'The "limit" parameter must be a positive number.' },
          { status: 400 }
        );
      }

      // Security: Prevent excessive data retrieval
      if (parsedLimit > MAX_LIMIT) {
        return NextResponse.json(
          { error: `Limit too high. Maximum ${MAX_LIMIT} results allowed.` },
          { status: 400 }
        );
      }

      limit = parsedLimit;
    }

    // Validate and parse page param
    let page = 1;
    if (pageParam !== null) {
      const parsedPage = parseInt(pageParam, 10);
      if (!isNaN(parsedPage) && parsedPage >= 1) {
        page = parsedPage;
      }
    }

    // 4. Construct the full backend URL with validated query parameters
    const targetUrl = new URL(`${backendBaseUrl}${backendPath}`);
    targetUrl.searchParams.append('query', query ?? '');
    targetUrl.searchParams.append('limit', limit.toString());
    targetUrl.searchParams.append('page', page.toString());

    // Forward optional vehicle filter params (for /search_tsbs)
    const makeParam = searchParams.get('make');
    const modelParam = searchParams.get('model');
    const yearParam = searchParams.get('year');
    if (makeParam) targetUrl.searchParams.append('make', makeParam);
    if (modelParam) targetUrl.searchParams.append('model', modelParam);
    if (yearParam && /^\d{4}$/.test(yearParam)) {
      targetUrl.searchParams.append('year', yearParam);
    }

    // 5. Set headers for the backend request (including the server-side API key)
    const headers = {
      'X-API-KEY': API_KEY,
      'Content-Type': 'application/json',
    };

    // 6. Make the request to the backend service with timeout
    // Security: Timeout prevents slowloris-style DoS attacks
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

    try {
      const backendResponse = await fetch(targetUrl.toString(), {
        method: 'GET',
        headers: headers,
        cache: 'no-store', // Ensure fresh data from backend
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      // 7. Handle backend response status
      if (!backendResponse.ok) {
        const errorBody = await backendResponse.text();
        console.error(
          `BACKEND ERROR for ${backendPath}: ${backendResponse.status} ${backendResponse.statusText}. Details: ${errorBody}`
        );
        return NextResponse.json(
          {
            error: 'Failed to retrieve data from the backend service.',
          },
          { status: 502 }
        );
      }

      // 8. Parse and return the successful backend response
      const data = await backendResponse.json();
      return NextResponse.json(data, { status: backendResponse.status });
    } catch (error) {
      clearTimeout(timeoutId);

      // Handle timeout errors specifically
      if (error instanceof Error && error.name === 'AbortError') {
        console.error(`TIMEOUT: Backend request to ${backendPath} exceeded ${REQUEST_TIMEOUT_MS}ms`);
        return NextResponse.json(
          { error: 'Request timeout. Backend service is slow to respond.' },
          { status: 504 }
        );
      }

      // Handle other network errors
      console.error(`NETWORK ERROR: Failed to proxy request to ${backendPath}:`, error);
      return NextResponse.json(
        { error: 'Failed to connect to the backend service.' },
        { status: 502 }
      );
    }
  };
}

// TODO: Add rate limiting (requires Redis or similar)
// See security-engineer report (agent a8a8f66) for implementation details
// Recommended: 100 requests per IP per 15 minutes
